### ISSUE TITLE
FSharp.Core missing when using dotnet 5.0

### ISSUE THREAD

**Issue by studio315b** [willnationsdev/godot-fsharp-tools#4]
If you update your project to .net 5.0, then attempt to load any F# project with a list in it, the game crashes on load.

MVP repo: https://github.com/studio315b/GodotFSharpMVP

**Comment by Devon7925** [comment]
Did you ever find a workaround to this?

**Comment by ShalokShalom** [comment]
What means in MVP in this context?

**Comment by jackmott** [comment]
I have run into this problem to, it seems to be some general FSharp -> Godot interaction problem when using dotnet 5.0, no idea what the deal is.

@ShalokShalom MVP means "minimal viable product" or smallest possible code that will reproduce.

**Comment by graffn0** [comment]
Try adding <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies> inside <PropertyGroup> in the root csproj (adding it to the fsproj didn't work for me). Source: https://github.com/godotengine/godot/issues/42271#issuecomment-751423827.

**Comment by studio315b** [comment]
@graffn0 that fixed it!

Sorry for the delayed response, finally got some time to test this out.
